//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLogSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parameter
    {
        public int Id { get; set; }
        public Nullable<int> DId { get; set; }
        public Nullable<int> MId { get; set; }
        public Nullable<int> EId { get; set; }
        public Nullable<int> TId { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<int> FId { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public string Datatype { get; set; }
        public Nullable<bool> IsNumber { get; set; }
        public Nullable<decimal> Min { get; set; }
        public Nullable<decimal> Max { get; set; }
        public string Regex { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Unit { get; set; }
        public string InpType { get; set; }
        public string InpValues { get; set; }
        public string InpField { get; set; }
        public Nullable<bool> IsDP { get; set; }
    }
}
