//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLogSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int Id { get; set; }
        public Nullable<int> DId { get; set; }
        public string Name { get; set; }
        public string Desc { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Remarks { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
